import type { Metadata } from "next";
import { Geist, Geist_Mono, Saira } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/UserContext";
import AuthNavbarWrapper from "./components/AuthNavbarWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const saira = Saira({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  style: ["normal", "italic"],
  variable: "--font-saira",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${saira.variable}`}>
      <body className="antialiased">
        <UserProvider>
          <AuthNavbarWrapper>
            {children}
          </AuthNavbarWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
